### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by zhanghaobucunzai** [sshan-zhao/GASDA#17]
vKITTI   which I have downloaded is jpg，but  the train.txt is png, what should i do to process them

**Comment by sshan-zhao** [comment]
> vKITTI which I have downloaded is jpg，but the train.txt is png, what should i do to process them

Did you try to replace .png with .jpg?

**Comment by zhanghaobucunzai** [comment]
/usr/local/python3.6.7/lib/python3.6/site-packages/torch/nn/functional.py:2941: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/user1/GASDA-master/models/networks.py:130: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format. (Triggered internally at  /pytorch/aten/src/ATen/native/TensorIterator.cpp:918.)
  sigma_xy = F.avg_pool2d(x*y, 3, 1) - mu_x*mu_y
(epoch: 1, iters: 32, lr: 1.000000e-04, time: 0.151, data: 5.862) R_Depth_Src: 2.215403 S_Depth_Tgt: 0.008330 R_Img_Tgt: 0.909889
(epoch: 1, iters: 64, lr: 1.000000e-04, time: 0.153, data: 0.000) R_Depth_Src: 1.338119 S_Depth_Tgt: 0.004384 R_Img_Tgt: 0.940811
(epoch: 1, iters: 96, lr: 1.000000e-04, time: 0.153, data: 0.007) R_Depth_Src: 1.033507 S_Depth_Tgt: 0.003214 R_Img_Tgt: 0.986949
(epoch: 1, iters: 128, lr: 1.000000e-04, time: 0.154, data: 0.000) R_Depth_Src: 0.812624 S_Depth_Tgt: 0.002983 R_Img_Tgt: 0.777155
(epoch: 1, iters: 160, lr: 1.000000e-04, time: 0.154, data: 0.000) R_Depth_Src: 0.758285 S_Depth_Tgt: 0.002648 R_Img_Tgt: 0.918045
(epoch: 1, iters: 192, lr: 1.000000e-04, time: 0.155, data: 0.000) R_Depth_Src: 0.845115 S_Depth_Tgt: 0.002078 R_Img_Tgt: 0.894601
(epoch: 1, iters: 224, lr: 1.000000e-04, time: 0.155, data: 0.000) R_Depth_Src: 0.878263 S_Depth_Tgt: 0.002062 R_Img_Tgt: 0.899929
(epoch: 1, iters: 256, lr: 1.000000e-04, time: 0.152, data: 0.000) R_Depth_Src: 0.697740 S_Depth_Tgt: 0.002119 R_Img_Tgt: 0.789803
(epoch: 1, iters: 288, lr: 1.000000e-04, time: 0.158, data: 0.000) R_Depth_Src: 0.766624 S_Depth_Tgt: 0.001632 R_Img_Tgt: 0.880449
(epoch: 1, iters: 320, lr: 1.000000e-04, time: 0.157, data: 0.000) R_Depth_Src: 0.570090 S_Depth_Tgt: 0.001451 R_Img_Tgt: 0.765347
(epoch: 1, iters: 352, lr: 1.000000e-04, time: 0.151, data: 0.000) R_Depth_Src: 0.456238 S_Depth_Tgt: 0.001822 R_Img_Tgt: 0.804739
(epoch: 1, iters: 384, lr: 1.000000e-04, time: 0.150, data: 0.000) R_Depth_Src: 0.437253 S_Depth_Tgt: 0.002167 R_Img_Tgt: 0.888291
(epoch: 1, iters: 416, lr: 1.000000e-04, time: 0.150, data: 0.000) R_Depth_Src: 0.451342 S_Depth_Tgt: 0.001789 R_Img_Tgt: 0.819866
(epoch: 1, iters: 448, lr: 1.000000e-04, time: 0.156, data: 0.002) R_Depth_Src: 0.800699 S_Depth_Tgt: 0.001326 R_Img_Tgt: 0.869186
(epoch: 1, iters: 480, lr: 1.000000e-04, time: 0.154, data: 0.000) R_Depth_Src: 0.378739 S_Depth_Tgt: 0.001441 R_Img_Tgt: 0.858967
(epoch: 1, iters: 512, lr: 1.000000e-04, time: 0.163, data: 0.000) R_Depth_Src: 0.591014 S_Depth_Tgt: 0.001151 R_Img_Tgt: 0.855171
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    for ind, data in enumerate(train_data_loader):
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/user1/GASDA-master/data/datasets.py", line 22, in __getitem__
    {dd.update(d[i]) for d in self.datasets if d is not None}
  File "/user1//GASDA-master/data/datasets.py", line 22, in <setcomp>
    {dd.update(d[i]) for d in self.datasets if d is not None}
  File "/user1/GASDA-master/data/datasets.py", line 156, in __getitem__
    l_img, r_img, fb, depth = self.read_data(datafiles)
  File "/user1/GASDA-master/data/datasets.py", line 139, in read_data
    r_rgb = Image.open(osp.join(self.root, datafiles['r_rgb'])).convert('RGB')
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/PIL/Image.py", line 915, in convert
    self.load()
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/usr/local/python3.6.7/lib/python3.6/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file

**Comment by sshan-zhao** [comment]
> /usr/local/python3.6.7/lib/python3.6/site-packages/torch/nn/functional.py:2941: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
> warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
> /user1/GASDA-master/models/networks.py:130: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format. (Triggered internally at /pytorch/aten/src/ATen/native/TensorIterator.cpp:918.)
> sigma_xy = F.avg_pool2d(x_y, 3, 1) - mu_x_mu_y
> (epoch: 1, iters: 32, lr: 1.000000e-04, time: 0.151, data: 5.862) R_Depth_Src: 2.215403 S_Depth_Tgt: 0.008330 R_Img_Tgt: 0.909889
> (epoch: 1, iters: 64, lr: 1.000000e-04, time: 0.153, data: 0.000) R_Depth_Src: 1.338119 S_Depth_Tgt: 0.004384 R_Img_Tgt: 0.940811
> (epoch: 1, iters: 96, lr: 1.000000e-04, time: 0.153, data: 0.007) R_Depth_Src: 1.033507 S_Depth_Tgt: 0.003214 R_Img_Tgt: 0.986949
> (epoch: 1, iters: 128, lr: 1.000000e-04, time: 0.154, data: 0.000) R_Depth_Src: 0.812624 S_Depth_Tgt: 0.002983 R_Img_Tgt: 0.777155
> (epoch: 1, iters: 160, lr: 1.000000e-04, time: 0.154, data: 0.000) R_Depth_Src: 0.758285 S_Depth_Tgt: 0.002648 R_Img_Tgt: 0.918045
> (epoch: 1, iters: 192, lr: 1.000000e-04, time: 0.155, data: 0.000) R_Depth_Src: 0.845115 S_Depth_Tgt: 0.002078 R_Img_Tgt: 0.894601
> (epoch: 1, iters: 224, lr: 1.000000e-04, time: 0.155, data: 0.000) R_Depth_Src: 0.878263 S_Depth_Tgt: 0.002062 R_Img_Tgt: 0.899929
> (epoch: 1, iters: 256, lr: 1.000000e-04, time: 0.152, data: 0.000) R_Depth_Src: 0.697740 S_Depth_Tgt: 0.002119 R_Img_Tgt: 0.789803
> (epoch: 1, iters: 288, lr: 1.000000e-04, time: 0.158, data: 0.000) R_Depth_Src: 0.766624 S_Depth_Tgt: 0.001632 R_Img_Tgt: 0.880449
> (epoch: 1, iters: 320, lr: 1.000000e-04, time: 0.157, data: 0.000) R_Depth_Src: 0.570090 S_Depth_Tgt: 0.001451 R_Img_Tgt: 0.765347
> (epoch: 1, iters: 352, lr: 1.000000e-04, time: 0.151, data: 0.000) R_Depth_Src: 0.456238 S_Depth_Tgt: 0.001822 R_Img_Tgt: 0.804739
> (epoch: 1, iters: 384, lr: 1.000000e-04, time: 0.150, data: 0.000) R_Depth_Src: 0.437253 S_Depth_Tgt: 0.002167 R_Img_Tgt: 0.888291
> (epoch: 1, iters: 416, lr: 1.000000e-04, time: 0.150, data: 0.000) R_Depth_Src: 0.451342 S_Depth_Tgt: 0.001789 R_Img_Tgt: 0.819866
> (epoch: 1, iters: 448, lr: 1.000000e-04, time: 0.156, data: 0.002) R_Depth_Src: 0.800699 S_Depth_Tgt: 0.001326 R_Img_Tgt: 0.869186
> (epoch: 1, iters: 480, lr: 1.000000e-04, time: 0.154, data: 0.000) R_Depth_Src: 0.378739 S_Depth_Tgt: 0.001441 R_Img_Tgt: 0.858967
> (epoch: 1, iters: 512, lr: 1.000000e-04, time: 0.163, data: 0.000) R_Depth_Src: 0.591014 S_Depth_Tgt: 0.001151 R_Img_Tgt: 0.855171
> Traceback (most recent call last):
> File "train.py", line 35, in 
> for ind, data in enumerate(train_data_loader):
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in **next**
> data = self._next_data()
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
> return self._process_data(data)
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
> data.reraise()
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
> raise self.exc_type(msg)
> OSError: Caught OSError in DataLoader worker process 2.
> Original Traceback (most recent call last):
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
> data = fetcher.fetch(index)
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in 
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/user1/GASDA-master/data/datasets.py", line 22, in **getitem**
> {dd.update(d[i]) for d in self.datasets if d is not None}
> File "/user1//GASDA-master/data/datasets.py", line 22, in 
> {dd.update(d[i]) for d in self.datasets if d is not None}
> File "/user1/GASDA-master/data/datasets.py", line 156, in **getitem**
> l_img, r_img, fb, depth = self.read_data(datafiles)
> File "/user1/GASDA-master/data/datasets.py", line 139, in read_data
> r_rgb = Image.open(osp.join(self.root, datafiles['r_rgb'])).convert('RGB')
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/PIL/Image.py", line 915, in convert
> self.load()
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/PIL/ImageFile.py", line 274, in load
> raise_oserror(err_code)
> File "/usr/local/python3.6.7/lib/python3.6/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
> raise OSError(message + " when reading image file")
> OSError: broken data stream when reading image file

It seems that there exist errors in your data files.
